check50:
  dependencies:
    - git+https://github.com/pazz/check50_java#egg=check50_java
  files:
    - !exclude "*"
    - !include "*.java"
    - !include "*.pdf"

submit50:
  slug: "liv-ac-uk/comp122/2020/resit"
  files:
    - !exclude "*"
    - !exclude ".class"
    - !include "*.java"
    - !include "*.pdf"
