check50:
  dependencies:
    - check50-java
  files:
    - !exclude "*"
    - !include "*.java"
    - !include "*.pdf"

submit50:
  slug: "liv-ac-uk/comp122/2020/resit"
  files:
    - !exclude "*"
    - !include "*.java"
    - !include "*.pdf"
